#!/bin/bash --login
#
#PBS -l select=1:ncpus=36
#PBS -l place=excl
#PBS -N bench
#PBS -A d167-s1770309
#PBS -l walltime=0:01:00

# Switch to current working directory
cd $PBS_O_WORKDIR

# load modules
module load intel-compilers-17
module load gcc

make -C src/ clean;

# spawn 1 thread
export OMP_NUM_THREADS=1

# Run the parallel program
make -C src/ run;

gprof -b src/MD src/gmon.out > src/gprof.txt
rm src/gmon.out

echo "Test results:";
python ./correctness.py;
