#!/bin/bash --login
#
#PBS -l select=1:ncpus=36
#PBS -l place=excl
#PBS -N bench
#PBS -A d167-s1770309
#PBS -l walltime=0:00:40
# initial -> walltime=1:40:0

# Switch to current working directory
cd $PBS_O_WORKDIR

rm ../bench.o*;
rm ../bench.e*;

# load modules
module load intel-compilers-17
module load gcc

make clean;

# spawn 1 thread
export OMP_NUM_THREADS=1


# Run the parallel program
make run_icc;

python ../correctness.py;
